### ISSUE TITLE
Addon crash after few hours

### ISSUE THREAD

**Issue by LiquidBlackNL** [cyberjunky/addon-p2000_rtlsdr#9]
Hi,

First of all, thank you for your work on this addon! Great work!

For me the addon crashes after an few hours with the following log data.
It seems this is triggered by the request to the OpenCageData API. May be relevant to https://github.com/cyberjunky/addon-p2000_rtlsdr/issues/6.

```
2024-02-01 07:10:18:  > hostname => core-mosquitto
2024-02-01 07:10:18:  > port => 1883
2024-02-01 07:10:18:  > username => addons
2024-02-01 07:10:18:  > client_id => p2000_rtlsdr
2024-02-01 07:10:18:  > base_topic => p2000_rtlsdr
2024-02-01 07:10:18:  > availability_topic => p2000_rtlsdr/status
2024-02-01 07:10:18:  > tls => None
2024-02-01 07:10:18: Database '/data/p2000.sqlite3' opened successfully
2024-02-01 07:10:18: Processing thread started
2024-02-01 07:10:18: Containing: 2509 places 83312 capcodes 4280 geocodes
2024-02-01 07:10:18: RTL-SDR process starting with: rtl_fm -f 169.65M -M fm -s 22050 | multimon-ng -a FLEX -t raw -
2024-02-01 07:10:18: Message receive thread started
Found 1 device(s):
multimon-ng 1.3.0
  (C) 1996/1997 by Tom Sailer HB9JNX/AE4WA
  (C) 2012-2023 by Elias Oenal
Available demodulators: POCSAG512 POCSAG1200 POCSAG2400 FLEX FLEX_NEXT EAS UFSK1200 CLIPFSK FMSFSK AFSK1200 AFSK2400 AFSK2400_2 AFSK2400_3 HAPN4800 FSK9600 DTMF ZVEI1 ZVEI2 ZVEI3 DZVEI PZVEI EEA EIA CCIR MORSE_CW DUMPCSV X10 SCOPE
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Tuner gain set to automatic.
Tuned to 169903575 Hz.
Oversampling input by: 46x.
Oversampling output by: 1x.
Buffer size: 8.08ms
Exact sample rate is: 1014300.020041 Hz
Sampling at 1014300 S/s.
Output at 22050 Hz.
Exception in thread ReceiveThread:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5152618c10>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.opencagedata.com', port=443): Max retries exceeded with url: /geocode/v1/json?q=Londensingel+%27s-Gravenhage&key=69348eba50f740bcac7767880bb859a3&limit=1&country=nl&language=nl (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5152618c10>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/p2000.py", line 1051, in receive_thread_call
    locations = OpenCageGeocode(address, self.opencagetoken)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p2000.py", line 209, in OpenCageGeocode
    response = requests.get('https://api.opencagedata.com/geocode/v1/json', params=params, timeout=5)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.opencagedata.com', port=443): Max retries exceeded with url: /geocode/v1/json?q=Londensingel+%27s-Gravenhage&key=69348eba50f740bcac7767880bb859a3&limit=1&country=nl&language=nl (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5152618c10>: Failed to establish a new connection: [Errno -3] Try again'))
```

My setup:
```
HA OS VM in ProxMox
Core: 2024.1.6
Supervisor: 2023.12.1
OS: 11.4
```

**Comment by cyberjunky** [comment]
Thank you, this is another missed error I think, I need to catch it in the code, I will have a look, it looks like you do too many requests to opencage API, too many alerts to geocode. I can fix the error but you will miss data, they are stored in a db for reuse so it can be temporary

**Comment by LiquidBlackNL** [comment]
Hmm, could this be caused by the fact that in my setup I have 3 sensors with various capcodes that sometimes match one and the same alarm? So the input from the 3 sensors is the same message. And of course the addon then very quickly makes multiple requests for the same message/address? (probably in the same second)

**Comment by cyberjunky** [comment]
That could be yes, never though about it like that

**Comment by LiquidBlackNL** [comment]
I will adjust my configuration for the troubleshoot so that all capcodes are put in the same sensor. I can imagine that this adjustment already fixes it.

I made this configuration because in Node-Red I distinguish between the shift I am on duty and the notifications that other shifts receive outside my duty week. But with certain alarms it happens that multiple teams receive the alarm and then you may experience the above behavior.

I will let you know! Thanks for the quick support!

**Comment by LiquidBlackNL** [comment]
The addon has not crashed so far since I adjusted my configuration as described above.
Also no more logs from the OpenCage API in the addon log up to now. :)
